import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { RoomEnvironment } from 'three/examples/jsm/environments/RoomEnvironment.js';
import type { TwinApi } from './model';
import { createAssetIPhone } from './assetModel';
import { IPhoneSyncClient } from './sync';
import './style.css';

declare global { interface Window { iPhoneTwin:TwinApi; __ready:boolean; setView:(name:string)=>void; __interactive:boolean } }
const app=document.querySelector<HTMLDivElement>('#app')!;app.dataset.theme='black';
app.innerHTML=`<main class="studio"><section class="stage" aria-label="iPhone 3D 预览"><canvas></canvas><div class="brand"><b>iPhone Twin Studio</b><span>REALTIME PRODUCT VISUALIZER</span></div><div class="stage-state"><i></i><span>实时渲染</span><b class="fps">60 FPS</b></div><div class="selection">正在载入高精度模型…</div></section><aside class="console"><header class="console-head"><div><span>IPHONE TWIN</span><h1>制作控制台</h1></div><button class="icon-btn collapse" aria-label="收起面板">›</button></header>
<section class="panel-section"><h2>场景</h2><div class="scene-grid two"><button class="scene-card" data-scene="white"><span class="scene-preview soft"></span><b>白色场景</b></button><button class="scene-card active" data-scene="black"><span class="scene-preview night"></span><b>黑色场景</b></button></div><div class="stage-tools"><button class="toggle-floor">隐藏阴影和底座</button></div><div class="screen-modes"><button class="active" data-screen-mode="model">模型屏幕</button><button data-screen-mode="live">手机投屏</button><button data-screen-mode="freeze">暂停画面</button></div></section>
<section class="panel-section"><h2>手机镜像</h2><button class="wide-action mirror">选择手机镜像窗口 <span>⌄</span></button><div class="status-line"><i class="mirror-dot"></i><div><b class="mirror-status">尚未连接</b><small>请选择 iPhone Twin Broadcast 窗口</small></div></div></section>
<section class="panel-section motion"><h2><span>姿态同步</span><button class="disclosure">⌄</button></h2><div class="status-line compact"><i class="sync-dot"></i><div><b class="sync-status">正在连接 Motion Server</b><small>等待 iPhone Controller</small></div></div><a class="pairing">等待 Controller 地址</a><div class="angles"><span>α <b data-angle="a">0.0°</b></span><span>β <b data-angle="b">0.0°</b></span><span>γ <b data-angle="g">0.0°</b></span><span>RATE <b data-angle="rate">0 Hz</b></span></div><code class="quat">q 0.000 0.000 0.000 1.000</code><label class="range-row">平滑 <input class="smooth" type="range" min="0" max="100" value="32"><output>0.15</output></label><button class="wide-action reset">重置姿态校准</button></section>
<section class="panel-section"><h2>高清输出</h2><div class="capture-grid"><button data-capture="4k">4K PNG</button><button data-capture="2k">2K PNG</button><button data-capture="web">网页截图</button></div><div class="two-up"><button class="record">开始 2K 录制 <i></i></button><button class="fullscreen">进入演示模式 <span>⛶</span></button></div><label class="check-row"><input type="checkbox" class="transparent"> 输出透明背景 <small>首次使用建议关闭</small></label></section>
<section class="panel-section director"><h2><span>镜头导演</span><button class="disclosure">⌄</button></h2><div class="director-grid"><button data-shot="hero">英雄登场<small>0s · 1</small></button><button data-shot="front">正面特写<small>0s · 2</small></button><button data-shot="orbit">侧转弧影<small>7s · 3</small></button><button data-shot="macro">镜头微距<small>7s · 4</small></button><button data-shot="top" class="active">顶部俯冲<small>6.5s · 5</small></button><button data-shot="final">终幕拉远<small>8s · 6</small></button></div><div class="speed"><button data-speed=".45">慢</button><button class="active" data-speed="1">标准</button><button data-speed="1.8">快</button></div><div class="transport"><button class="pause">暂停</button><button class="play">播放</button><button class="stop">停止</button></div><div class="timeline"><span></span></div><div class="timecode">00:00 / 00:28</div><p class="director-state">顶部俯冲已停止<small>数字键 1–6 选镜 · Space 播放 · 0 停止</small></p></section>
<section class="panel-section views"><h2>视角</h2><button data-view="three" class="active wide">三分之四</button><div class="view-grid"><button data-view="rear">背面</button><button data-view="front">正面</button><button data-view="right">右侧</button><button data-view="left">左侧</button><button data-view="topview">顶部</button><button data-view="bottom">底部</button></div></section></aside></main>`;

const stage=app.querySelector<HTMLElement>('.stage')!,canvas=app.querySelector('canvas')!,selected=app.querySelector<HTMLElement>('.selection')!;
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x151922);scene.environment=new THREE.PMREMGenerator(renderer).fromScene(new RoomEnvironment(),.04).texture;
const camera=new THREE.PerspectiveCamera(31,1,.1,160),controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.target.set(0,0,0);controls.minDistance=28;controls.maxDistance=80;
const hemi=new THREE.HemisphereLight(0xeaf1ff,0x16131b,1.6),key=new THREE.DirectionalLight(0xf5f7ff,3.4),rim=new THREE.DirectionalLight(0x7894dd,2.1);key.position.set(-7,11,8);key.castShadow=true;key.shadow.mapSize.set(2048,2048);rim.position.set(9,6,-9);const movingLightA=new THREE.PointLight(0x89a7ff,18,38,2),movingLightB=new THREE.PointLight(0xffaa83,12,34,2);scene.add(hemi,key,rim,movingLightA,movingLightB);
const backdropMaterial=new THREE.MeshStandardMaterial({color:0x161a22,roughness:.92,metalness:0,side:THREE.BackSide}),backdrop=new THREE.Mesh(new THREE.SphereGeometry(55,48,32),backdropMaterial);scene.add(backdrop);
const floorMaterial=new THREE.MeshStandardMaterial({color:0x171b25,roughness:.82,metalness:.05}),floor=new THREE.Mesh(new THREE.CircleGeometry(17,96),floorMaterial);floor.rotation.x=-Math.PI/2;floor.position.y=-8.65;floor.receiveShadow=true;scene.add(floor);
const phone=createAssetIPhone('/models/iphone17/iphone-17-pro-max.glb',()=>selected.textContent=`${phone.clickable.length} 个部件 · GLB 模型已载入`);phone.root.rotation.set(-.12,-.45,.05);scene.add(phone.root);window.iPhoneTwin=phone.api;phone.ready.catch(error=>{console.error(error);selected.textContent=`模型加载失败 · ${error instanceof Error?error.message:'未知错误'}`});
const setText=(selector:string,text:string)=>{const el=app.querySelector<HTMLElement>(selector);if(el)el.textContent=text};const markScreenMode=(mode:'model'|'live'|'freeze')=>app.querySelectorAll('[data-screen-mode]').forEach(item=>item.classList.toggle('active',(item as HTMLElement).dataset.screenMode===mode));let lastMotion=performance.now(),screenModeManuallyChosen=false;
const sync=new IPhoneSyncClient(phone.api,status=>{setText('.sync-status',{connecting:'正在连接 Motion Server',connected:'已连接，等待 iPhone',streaming:'姿态同步中',screen:'屏幕与姿态同步中',disconnected:'连接已断开',error:'连接错误'}[status]);app.querySelector('.sync-dot')?.setAttribute('data-status',status);if(status==='screen'&&!screenModeManuallyChosen){markScreenMode('live');setText('.mirror-status','正在显示手机投屏')}},q=>{const now=performance.now(),hz=Math.round(1000/Math.max(1,now-lastMotion));lastMotion=now;const e=new THREE.Euler().setFromQuaternion(new THREE.Quaternion(q.x,q.y,q.z,q.w),'YXZ');setText('[data-angle=a]',`${THREE.MathUtils.radToDeg(e.x).toFixed(1)}°`);setText('[data-angle=b]',`${THREE.MathUtils.radToDeg(e.y).toFixed(1)}°`);setText('[data-angle=g]',`${THREE.MathUtils.radToDeg(e.z).toFixed(1)}°`);setText('[data-angle=rate]',`${hz} Hz`);setText('.quat',`q ${q.x.toFixed(3)} ${q.y.toFixed(3)} ${q.z.toFixed(3)} ${q.w.toFixed(3)}`)});
sync.pairing().then(({url,token})=>{setText('.pairing',`Controller · ${location.hostname}:8765 · ${token.slice(0,6)}`);sync.connect(url)}).catch(()=>setText('.sync-status','请启动同步服务'));
const views:Record<string,[number,number,number]>= {front:[0,.2,59],rear:[0,.2,-59],three:[26,9.5,59],right:[59,.2,0],left:[-59,.2,0],topview:[0,59,.01],bottom:[0,-55,.01]};window.__interactive=false;window.setView=name=>{const v=views[name]||views.three;camera.position.set(...v);camera.lookAt(0,0,0);controls.target.set(0,0,0);controls.update();window.__interactive=false;app.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',(b as HTMLElement).dataset.view===name))};window.setView('three');controls.addEventListener('start',()=>window.__interactive=true);app.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>b.onclick=()=>window.setView(b.dataset.view!));
const themes={white:{bg:0xe7e7e4,floor:0xd6d5d1,backdrop:0xe2e3e5,key:0xfff4e5,rim:0x9eb8e8,moveA:0x90b4ff,moveB:0xffc5a1,exposure:.92},black:{bg:0x151922,floor:0x252a34,backdrop:0x161a22,key:0xf5f7ff,rim:0x7894dd,moveA:0x668cff,moveB:0xd68068,exposure:.88}};app.querySelectorAll<HTMLButtonElement>('[data-scene]').forEach(button=>button.onclick=()=>{const name=button.dataset.scene as keyof typeof themes,t=themes[name];app.dataset.theme=name;scene.background=new THREE.Color(t.bg);floorMaterial.color.setHex(t.floor);backdropMaterial.color.setHex(t.backdrop);key.color.setHex(t.key);rim.color.setHex(t.rim);movingLightA.color.setHex(t.moveA);movingLightB.color.setHex(t.moveB);renderer.toneMappingExposure=t.exposure;app.querySelectorAll('[data-scene]').forEach(x=>x.classList.toggle('active',x===button))});
app.querySelector<HTMLButtonElement>('.mirror')!.onclick=async()=>{try{const stream=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:30},audio:false});phone.api.setScreenStream(stream);setText('.mirror-status','镜像已连接');app.querySelector('.mirror-dot')?.classList.add('online');stream.getVideoTracks()[0].addEventListener('ended',()=>{setText('.mirror-status','尚未连接');app.querySelector('.mirror-dot')?.classList.remove('online')})}catch{setText('.mirror-status','已取消选择')}};app.querySelector<HTMLButtonElement>('.reset')!.onclick=()=>{phone.api.resetOrientation();phone.root.quaternion.identity();window.setView('front');setText('.director-state','已校准 · 正面垂直于地面')};app.querySelector<HTMLInputElement>('.smooth')!.oninput=e=>setText('.range-row output',(Number((e.target as HTMLInputElement).value)/210).toFixed(2));app.querySelector<HTMLButtonElement>('.fullscreen')!.onclick=()=>document.fullscreenElement?document.exitFullscreen():app.requestFullscreen();
function downloadBlob(blob:Blob,name:string){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function capturePng(mode:'4k'|'2k'|'web'){const [w,h]=mode==='4k'?[3840,2160]:mode==='2k'?[2560,1440]:[stage.clientWidth,stage.clientHeight];const old=renderer.getSize(new THREE.Vector2()),ratio=renderer.getPixelRatio();renderer.setPixelRatio(1);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.render(scene,camera);canvas.toBlob(blob=>blob&&downloadBlob(blob,`iphone-17-pro-${w}x${h}.png`));renderer.setPixelRatio(ratio);renderer.setSize(old.x,old.y,false);resize()}app.querySelectorAll<HTMLButtonElement>('[data-capture]').forEach(button=>button.onclick=()=>capturePng(button.dataset.capture as '4k'|'2k'|'web'));
let recorder:MediaRecorder|null=null,chunks:Blob[]=[];app.querySelector<HTMLButtonElement>('.record')!.onclick=()=>{const button=app.querySelector<HTMLButtonElement>('.record')!;if(recorder?.state==='recording'){recorder.stop();button.classList.remove('recording');button.firstChild!.textContent='开始 2K 录制 ';return}chunks=[];recorder=new MediaRecorder(canvas.captureStream(30),{mimeType:'video/webm;codecs=vp9'});recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.onstop=()=>downloadBlob(new Blob(chunks,{type:'video/webm'}),'iphone-twin-2k.webm');recorder.start();button.classList.add('recording');button.firstChild!.textContent='停止并保存 '};
const shots:Record<string,{view:string;label:string}>={hero:{view:'three',label:'英雄登场'},front:{view:'front',label:'正面特写'},orbit:{view:'right',label:'侧转弧影'},macro:{view:'front',label:'镜头微距'},top:{view:'topview',label:'顶部俯冲'},final:{view:'rear',label:'终幕拉远'}};let playing=false,playStart=0,directorSpeed=1;app.querySelectorAll<HTMLButtonElement>('[data-shot]').forEach(button=>button.onclick=()=>{const shot=shots[button.dataset.shot!];window.setView(shot.view);if(button.dataset.shot==='macro')camera.position.multiplyScalar(.7);app.querySelectorAll('[data-shot]').forEach(x=>x.classList.toggle('active',x===button));setText('.director-state',`${shot.label}已停止`)});app.querySelectorAll<HTMLButtonElement>('[data-speed]').forEach(button=>button.onclick=()=>{directorSpeed=Number(button.dataset.speed);app.querySelectorAll('[data-speed]').forEach(x=>x.classList.toggle('active',x===button))});app.querySelector<HTMLButtonElement>('.play')!.onclick=()=>{playing=true;playStart=performance.now();setText('.director-state','镜头导演播放中')};app.querySelector<HTMLButtonElement>('.pause')!.onclick=()=>{playing=false;setText('.director-state','镜头导演已暂停')};app.querySelector<HTMLButtonElement>('.stop')!.onclick=()=>{playing=false;window.setView('three');setText('.director-state','镜头导演已停止');(app.querySelector('.timeline span') as HTMLElement).style.width='0%';setText('.timecode','00:00 / 00:28')};addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();(app.querySelector('.play') as HTMLButtonElement).click()}if(e.key==='0')(app.querySelector('.stop') as HTMLButtonElement).click();if(/[1-6]/.test(e.key))app.querySelectorAll<HTMLButtonElement>('[data-shot]')[Number(e.key)-1]?.click()});
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();canvas.addEventListener('pointerup',e=>{const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(phone.clickable,true)[0],id=phone.select(hit?.object??null);selected.textContent=id?`已选择 · ${id}`:`${phone.clickable.length} 个部件 · 点击模型检查`});const collapseButton=app.querySelector<HTMLButtonElement>('.collapse')!;collapseButton.onclick=()=>{const collapsed=app.classList.toggle('console-collapsed');collapseButton.setAttribute('aria-label',collapsed?'展开面板':'收起面板');requestAnimationFrame(resize)};
app.querySelector<HTMLInputElement>('.transparent')!.onchange=e=>{const activeTheme=(app.dataset.theme==='white'?'white':'black') as keyof typeof themes;scene.background=(e.target as HTMLInputElement).checked?null:new THREE.Color(themes[activeTheme].bg)};
let floorHidden=false;app.querySelector<HTMLButtonElement>('.toggle-floor')!.onclick=()=>{floorHidden=!floorHidden;floor.visible=!floorHidden;renderer.shadowMap.enabled=!floorHidden;phone.root.traverse(object=>{if(object instanceof THREE.Mesh){object.castShadow=!floorHidden;object.receiveShadow=!floorHidden}});setText('.toggle-floor',floorHidden?'显示阴影和底座':'隐藏阴影和底座')};
app.querySelectorAll<HTMLButtonElement>('[data-screen-mode]').forEach(button=>button.onclick=()=>{const mode=button.dataset.screenMode as 'model'|'live'|'freeze';screenModeManuallyChosen=true;phone.api.setScreenMode(mode);markScreenMode(mode);setText('.mirror-status',{model:'正在显示模型原始屏幕',live:'正在显示手机投屏',freeze:'投屏画面已暂停'}[mode])});
app.querySelector<HTMLButtonElement>('.mirror')!.onclick=async()=>{try{const stream=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:30},audio:false});phone.api.setScreenStream(stream);screenModeManuallyChosen=false;markScreenMode('live');setText('.mirror-status','镜像已连接');app.querySelector('.mirror-dot')?.classList.add('online');stream.getVideoTracks()[0].addEventListener('ended',()=>{setText('.mirror-status','尚未连接');app.querySelector('.mirror-dot')?.classList.remove('online')})}catch{setText('.mirror-status','已取消选择')}};
function resize(){const r=stage.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;if(innerWidth>800&&!app.classList.contains('console-collapsed')){const consoleWidth=app.querySelector<HTMLElement>('.console')!.getBoundingClientRect().width+24;camera.setViewOffset(r.width,r.height,consoleWidth/2,0,r.width,r.height)}else camera.clearViewOffset();camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();let frames=0,fpsAt=performance.now();renderer.setAnimationLoop(t=>{phone.tick(t);const seconds=t*.001;movingLightA.position.set(Math.sin(seconds*.34)*17,5+Math.sin(seconds*.23)*5,-7+Math.cos(seconds*.34)*9);movingLightB.position.set(Math.cos(seconds*.27)*15,-2+Math.sin(seconds*.31)*7,8+Math.sin(seconds*.27)*7);if(window.__interactive)controls.update();if(playing){const elapsed=((t-playStart)*.001*directorSpeed)%28,progress=elapsed/28;(app.querySelector('.timeline span') as HTMLElement).style.width=`${progress*100}%`;setText('.timecode',`00:${String(Math.floor(elapsed)).padStart(2,'0')} / 00:28`);const angle=progress*Math.PI*2;camera.position.set(Math.sin(angle)*53,8+Math.sin(angle*2)*11,Math.cos(angle)*53);camera.lookAt(0,0,0)}renderer.render(scene,camera);frames++;if(t-fpsAt>1000){setText('.fps',`${Math.round(frames*1000/(t-fpsAt))} FPS`);frames=0;fpsAt=t}window.__ready=true});
